### ISSUE TITLE
GUI Testing Bugs (15 August 2019)

### ISSUE THREAD

**Issue by NausheenSS** [dicelab-rhul/vacuumworld#1]
1. It would be better if you put tooltips for buttons.
2. GUI gets exit on the file upload button(the button to the down right)
3. One can place dirt on a location occupied by an agent. 
4. One can reset a running simulation and then place some more agents and then resume. Is it resuming properly or refreshing the minds?
5.  One can place new dirt on an already dirty location. 

_________________________________________________Nausheen__________________________________________

**Comment by BenedictWilkinsAI** [comment]
1. in progress
2. fixed load button crash with empty file name
3. You should be able to place dirt where there is an agent, the bug was that it was being placed on top and not under.
4. It works as it should? when the environment is reset (by pressing the reset button) the minds are also reset, otherwise they are not (e.g. on pause or stop).
5. This is intended - as long as the new dirt is placed in the grid? I will check.

NOTE: in future please create an 1 issue for each issue and dont list them in one. Otherwise I cant keep track of these that have been addressed.

Best,
Ben
