### ISSUE TITLE
(Lack of) SIGINT and SIGTSTP management, and related bugs

### ISSUE THREAD

**Issue by BenedictWilkinsAI** [dicelab-rhul/vacuumworld#13]
CTRL z leaves UI hanging
CTRL c has no effect

**Comment by cloudstrife9999** [comment]
As of fdc424f, the issue with SIGINT (CTRL+C) has been fixed by catching a KeyboardInterrupt and exiting cleanly.

Also, as of fdc424f, the issue with SIGTSTP (CTRL+Z) has been mitigated by making VacuumWorld explicitly ignore such signal.

If the fix and the mitigation are satisfactory (CC @BenedictWilkinsAI) we can close the issue.

**Comment by BenedictWilkinsAI** [comment]
@cloudstrife9999 on my machine it does not exit on SIGINT I just get a message?

**Comment by BenedictWilkinsAI** [comment]
@cloudstrife9999 also why do we ignore SIGSTP and not just exit cleanly?

**Comment by BenedictWilkinsAI** [comment]
now exits cleanly on db829c2

**Comment by cloudstrife9999** [comment]
@BenedictWilkinsAI 

- About SIGINT: on my computer it did work (only after a few seconds, though).

- About SIGTSTP: it's meaning is that the program should be interrupted, but should also be able to be resumed. However, apparently it does not work properly. That's why, as a placeholder, I made it so that it ignores the signal.

If we agree to treat SIGTSTP as a SIGINT, then we can couple the behaviour.

**Comment by cloudstrife9999** [comment]
As the problem seems to be fixed, I'm closing the issue.

**Comment by cloudstrife9999** [comment]
This issue was really fixed only by #27.
