### ISSUE TITLE
Mac image loading error

### ISSUE THREAD

**Issue by Occy88** [dicelab-rhul/vacuumworld#7]
issues with loading images with tkinter.
Fix is available

[vwv.py.zip](https://github.com/dicelab-rhul/vacuumworld/files/3707121/vwv.py.zip)

**Comment by BenedictWilkinsAI** [comment]
Hello Occy88,

I have fixed this issue, it came about because I wanted to remove the use of PIL altogether and only rely on tk but it turns out tk cant read .png (as far as i know..? this seemed to be the problem).

Thank you for flagging this!

The pip repository will be updated when testing a full test has been done.
We would be grateful if you could confirm the issue has been fixed by cloning the most recent version.

Best,
Ben

**Comment by Occy88** [comment]
no problem will do

**Comment by Occy88** [comment]
Issue has been fixed.
